import pygame

PLANET_TERRA1 = 1
PLANET_TERRA2 = 2
PLANET_KEERGAN = 3

PLANETS = (
    (PLANET_TERRA1, (0, 0, -150)),
    (PLANET_KEERGAN, (0, 0, 150)),
)

IDS_TO_NAMES = {
    PLANET_TERRA1: "Terra1",
    PLANET_TERRA2: "Gemini2",
    PLANET_KEERGAN: "Keergan",
}
